#!/usr/bin/env ruby

git_bundles = [ 
        "git://github.com/astashov/vim-ruby-debugger.git",
        "git://github.com/msanders/snipmate.vim.git",
        "git://github.com/scrooloose/nerdtree.git",
        "git://github.com/tpope/vim-git.git",
        "git://github.com/vim-ruby/vim-ruby.git",
        "git://github.com/Rip-Rip/clang_complete.git",
        "git://github.com/vim-scripts/autoload_cscope.vim.git",
        #"file:///Users/rickard/Code/vim/project.vim",
        "git://github.com/spf13/vim-colors.git",
        "git://github.com/noah/vim256-color.git",
        "git://github.com/rickard/project.vim",
]

vim_org_scripts = []

require 'fileutils'
require 'open-uri'

def install_pathogen(url)
    pg_dir = File.join(File.dirname(__FILE__), "pathogen")
    wd = FileUtils.getwd
    FileUtils.mkdir_p(pg_dir)
    FileUtils.cd(pg_dir)
    dir = url.split('/').last.sub(/\.git$/, '')
    `git clone #{url} #{dir}`
    FileUtils.cd(wd)
    puts "#{FileUtils.getwd}: mv #{pg_dir}/#{dir}/autoload "
    FileUtils.mv "#{pg_dir}/#{dir}/autoload", "autoload"
    FileUtils.rm_rf pg_dir
end

if File.exists?("autoload")
    puts "autoload/ already exists, not upgrading pathogen"
else
    install_pathogen("git://github.com/tpope/vim-pathogen.git")
end

bundles_dir = File.join(File.dirname(__FILE__), "bundle")
FileUtils.mkdir_p(bundles_dir)
FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
        dir = url.split('/').last.sub(/\.git$/, '')
        puts "  Unpacking #{url} into #{dir}"
        `git clone #{url} #{dir}`
        FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
        puts "  Downloading #{name}"
        local_file = File.join(name, script_type, "#{name}.vim")
        FileUtils.mkdir_p(File.dirname(local_file))
        File.open(local_file, "w") do |file|
                file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
        end
end
